name: toy_model_interpretability
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python==3.10.6
  - plotly==5.10.0
  - pytorch==1.12.1
  - numpy==1.23.4
  - pytest==7.1.3
  - pandas==1.5.0
  - torchvision==0.13.0
  - tqdm==4.64.1
  - wandb==0.13.5
  - matplotlib==3.6.2
  - pip: 
    - torch-optimizer==0.3.0
    - streamlit==1.15.1
    - streamlit-option-menu==0.3.2
    - pytest==7.1.3
    - pytest-cov==4.0.0